# Generated by Django 2.1.4 on 2019-01-06 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_alive', models.DateTimeField(verbose_name='last contact')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('photo', models.ImageField(upload_to='photos')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node_manager.Node')),
            ],
        ),
    ]
