# Generated by Django 2.1.4 on 2019-01-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='is_alive',
            new_name='last_contact',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
