# Generated by Django 2.1.4 on 2019-01-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0002_auto_20190106_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='last_contact',
            field=models.DateTimeField(editable=False, null=True, verbose_name='last contact'),
        ),
    ]
