# Generated by Django 2.1.4 on 2019-01-23 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_manager', '0004_auto_20190123_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='node',
            name='contact',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
